### ISSUE TITLE
URLs without a trailing "/" have dead image links

### ISSUE THREAD

**Issue by plaes** [opulo-inc/docs#161] opened 2024-11-07 10:40 UTC
The placement error images are not showing correctly:  https://docs.opulo.io/openpnp/debugging

Apparently there's a link somewhere where the final slash is not correctly applied: `https://docs.opulo.io/openpnp/debugging/` vs `https://docs.opulo.io/openpnp/debugging`

Broken link is at the end of this page: https://docs.opulo.io/openpnp/ftp/3-test-run/#step-through-the-job

**Comment by atanisoft** [comment] 2024-11-07 13:12
this is a duplicate of https://github.com/opulo-inc/docs/issues/159 but you have provided more details on it than I delved into.

**Comment by sphawes** [comment] 2024-11-12 19:12
Thanks for the report @plaes and @atanisoft! I think this is the result of our new docs hosting, DigitalOcean, not redirecting urls without a trailing slash to one with a trailing slash. Github Pages does this automatically.

@theacodes lmk if you want access to our digitalocean account if that's helpful in figuring it out!

**Comment by theacodes** [comment] 2024-11-13 15:29
Okay, this was caused by two issues:

1. There were several instances of us improperly linking to other pages within MkDocs. MkDocs _really_ wants internal URLs to be in the form of `../relative/path/to/thing/index.md`. In this case, we'd linked to `../../debugging` instead of `../../debugging/index.md`. I have fixed _all_ occurrences of this in the codebase, which makes MkDocs create the correct link with trailing slash.
2. DigitalOcean does not automatically insert trailing slashes like GitHub Pages does ([ref1](https://github.com/slorber/trailing-slash-guide), [ref2](https://ideas.digitalocean.com/app-platform/p/trailing-slash-on-directories). GitHub Pages was actually saving us from our own mistakes, but DigitalOcean doesn't!

With internal links fixed, this should no longer be an issue when just navigating the documentation. Any links in the wild that are missing the trailing slash may still cause issues.

Fixed in e9191c4f4

**Closed by theacodes** 2024-11-13 15:29 UTC
